import os
from dotenv import load_dotenv

load_dotenv()

AZURE_BLOB_CONN_STR = os.getenv("AZURE_BLOB_CONN_STR")
AZURE_CONTAINER_NAME = os.getenv("AZURE_CONTAINER_NAME", "rag-data")

# Azure Chat LLM
AZURE_CHAT_API_KEY = os.getenv("AZURE_CHAT_API_KEY")
AZURE_CHAT_ENDPOINT = os.getenv("AZURE_CHAT_ENDPOINT")
AZURE_CHAT_API_VERSION = os.getenv("AZURE_CHAT_API_VERSION")
AZURE_CHAT_MODEL = os.getenv("AZURE_CHAT_MODEL")

# Embeddings
AZURE_EMBEDDINGS_API_KEY = os.getenv("AZURE_EMBEDDINGS_API_KEY")
AZURE_EMBEDDINGS_ENDPOINT = os.getenv("AZURE_EMBEDDINGS_ENDPOINT")
AZURE_EMBEDDINGS_DEPLOYMENT = os.getenv("AZURE_EMBEDDINGS_DEPLOYMENT")
AZURE_EMBEDDING_API_VERSION = os.getenv("AZURE_EMBEDDING_API_VERSION")

# Cost
MODEL_INPUT_PRICE = float(os.getenv("MODEL_INPUT_PRICE", 0))
MODEL_OUTPUT_PRICE = float(os.getenv("MODEL_OUTPUT_PRICE", 0))

# FAISS/BM25 storage filenames
FAISS_INDEX_FILE = os.getenv("FAISS_INDEX_FILE")
FAISS_STORE_FILE = os.getenv("FAISS_STORE_FILE")
BM25_FILE = os.getenv("BM25_FILE")
PDF_CHUNK_MAP_FILE = os.getenv("PDF_CHUNK_MAP_FILE")

PDF_FOLDER=os.getenv("PDF_FOLDER")
INDEX_FOLDER=os.getenv("INDEX_FOLDER")
